# Generated by Django 3.2.6 on 2023-10-19 15:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='valor_rating',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(auto_now=True)),
                ('estado_atual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativa_atual', to='selfapp.alternativa')),
                ('estado_desejado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternativa_desejada', to='selfapp.alternativa')),
                ('id_pergunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pergunta_resposta', to='selfapp.pergunta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
