# Generated by Django 3.2.6 on 2023-10-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfapp', '0002_auto_20231019_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='descricao',
            field=models.TextField(default='TESTE', max_length=300, null=True),
        ),
    ]
