# Generated by Django 3.2.6 on 2023-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfapp', '0003_pergunta_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='link_doc',
            field=models.TextField(default='https://www.z-act.io/', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='descricao',
            field=models.TextField(default='Descrição - Pergunta', max_length=300, null=True),
        ),
    ]
