# Generated by Django 3.2.6 on 2023-10-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfapp', '0004_auto_20231026_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='descricao',
            field=models.TextField(default='Descrição - Pergunta', max_length=400, null=True),
        ),
    ]
